version: "3"

services:
  backend:
    container_name: backend
    restart: always
    image: jams2808/ayd2_backend:latest
    ports:
      - "8080:8080"
    expose:
      - "8000"

  frontend:
    container_name: frontend
    restart: always
    image: jams2808/ayd2_frontend:latest
    environment:
      - VITE_API=http://34.16.176.103:8080/
      - VITE_S3=https://6fcsiupqnc.execute-api.us-east-2.amazonaws.com/default/getPresignedURL
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend